version: '3'

services:
  front:
    build: ./frontend
    container_name: udemy-docker-front
    command: serve -s build -l 3000
    ports:
      - "3000:3000"
#    restart: unless-stopped
#    stdin_open: true
#    tty: true
#    volumes:
#      - ./frontend/src:/usr/src/app/src

  api:
    build: ./api
    container_name: udemy-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://rworld.com
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: udemy-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://rworld.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  api_db:
    image: mongo:latest
    container_name: udemy-docker-db
    volumes:
      - mongodb_api:/data/db

  auth_db:
    image: mongo:latest
    container_name: udemy-docker-auth-db
    volumes:
      - mongodb_auth:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: udemy-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf

volumes:
  mongodb_api:
  mongodb_auth: